package com.cqu.genaiexpensetracker.ai_insights;

import java.util.List;

/**
 * Represents the response structure returned by the Gemini API.
 * This class is used to parse the JSON response from the generative model.
 */
public class GeminiResponse {

    /** A list of generated candidates from the Gemini model. */
    public List<Candidate> candidates;

    /**
     * Represents a single candidate in the response.
     * Each candidate contains content generated by the model.
     */
    public static class Candidate {

        /** The main content block of the candidate. */
        public Content content;
    }

    /**
     * Represents the content within a candidate.
     * Contains one or more parts, which hold textual output.
     */
    public static class Content {

        /** The list of parts (typically one) containing generated text. */
        public List<Part> parts;
    }

    /**
     * Represents a single part of the content.
     * Typically includes a segment of generated text.
     */
    public static class Part {

        /** The actual generated text from the Gemini model. */
        public String text;
    }
}
